## Kaleigh Strohl  |  ECON833: Problem Set 2

### Standard Library, Problems 1/2/3

#### Problem 1

In [1]:
my_list = [1, 2, 3, 4, 5]
print(min(my_list), max(my_list), (sum(my_list) / 5) )

1 5 3.0


#### 
#### Problem 2

In [2]:
price = 2
new_price = price
new_price = 3
price == new_price

False

In [7]:
string = "a"
another_string = string
another_string = "ab"
string == another_string

False

In [12]:
another_list = my_list
my_list[1] = 0
my_list == another_list

True

In [13]:
my_tuple = (5, 6, 7)
another_tuple = my_tuple
my_tuple += (1,)
my_tuple == another_tuple

False

In [18]:
my_set = {1: 'a', 2: 'b', 3: 'c'}
another_set = my_set
another_set[3] = 'd'
my_set == another_set

True

##### Conclusions: 
##### Integers, strings, and tuples are immutable
##### Lists and sets are mutable

#### 
#### Problem 3

In [4]:
import calculator as calc

In [7]:
side1 = 3 
side2 = 4
hypotenuse = calc.sqrt(calc.sum_of_arg(calc.multiply(side1, side1), calc.multiply(side2, side2)))
hypotenuse

5.0

### 
###
### Introduction to NumPy, Problems 1/2/5

#### Problem 1

In [155]:
import numpy as np

In [156]:
A = np.array([[3, -1, 4], [1, 5, -9]])
A

array([[ 3, -1,  4],
       [ 1,  5, -9]])

In [157]:
B = np.array([[2, 6, -5, 3], [5, -8, 9, 7], [9, -3, -2, -3]])
B

array([[ 2,  6, -5,  3],
       [ 5, -8,  9,  7],
       [ 9, -3, -2, -3]])

In [158]:
A @ B

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

#### 
#### Problem 2

In [159]:
A = np.array([[3, 1, 4],[1, 5, 9],[-5, 3, 1]])
A

array([[ 3,  1,  4],
       [ 1,  5,  9],
       [-5,  3,  1]])

In [163]:
-(A*A*A) + 9*A*A - 15*A

array([[   9,   -7,   20],
       [  -7,   25, -135],
       [ 425,    9,   -7]])

#### 
#### Problem 5

In [184]:
A = np.arange(6).reshape((2,3))
B = np.tril(np.full((3, 3), 3))
C = np.diag([-2, -2, -2])

In [191]:
D = np.vstack((np.zeros((3, 3)), A, B))
D

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 2.],
       [3., 4., 5.],
       [3., 0., 0.],
       [3., 3., 0.],
       [3., 3., 3.]])

In [186]:
E = np.vstack(((A.T), (np.zeros((5, 2)))))
E

array([[0., 3.],
       [1., 4.],
       [2., 5.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [197]:
F = np.vstack(((np.eye(3)), (np.zeros((2, 3))), C))
F

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [-2.,  0.,  0.],
       [ 0., -2.,  0.],
       [ 0.,  0., -2.]])

In [198]:
block = np.hstack((D, E, F))
block

array([[ 0.,  0.,  0.,  0.,  3.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  4.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  2.,  5.,  0.,  0.,  1.],
       [ 0.,  1.,  2.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  4.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -2.]])

###
### 
### Object Oriented Programming, Problems 1/2

#### Problem 1

In [91]:
class Backpack:
    """
    A Backpack object class. Has a name and a list of contents.
    
    Attributes: 
        name (str): the name of the backpack's owner.
        color (str): the color of the backpack.
        max_size (int): maximum number of items in the backpack. 
        contents (list): the contents of the backpack.
    """
    def __init__(self, name, color, max_size=5):
        """Set the name, color, max size, and initialize an empty list of contents.
        
        Parameters: 
            name (str): the name of the backpack's owner.
            color (str): the color of the backpack.
            max_size (float): maximum number of items in the backpack.
        """
        self.name = name
        self.color = color
        self.max_size = 5
        self.contents = []
    
    def put(self, item):
        """Add 'item' to the backpack's list of contents, 
        conditional on the number of items presently in the backpack does not exceed capacity"""
        if len(self.contents) == self.max_size:
            print("No Room!")
        else:
            self.contents.append(item)

    def take(self, item):
        """Remove 'item' from the backpack's list of contents."""
        self.contents.remove(item)
        
    def dump(self):
        """Resets the contents of the backpack to an empty list."""
        self.contents = []

In [87]:
my_backpack = Backpack("Kaleigh", "blue")
print(my_backpack.name, my_backpack.color, my_backpack.contents)

Kaleigh blue []


In [88]:
my_backpack.put("eraser")
my_backpack.contents

['eraser']

In [89]:
def test_backpack(): 
    testpack = Backpack("Kaleigh", "blue")
    if testpack.name != "Kaleigh":
        print("Backpack.name assigned incorrectly")
    for item in ["pencil", "pen", "paper", "computer"]:
        testpack.put(item)
    print("Contents:", testpack.contents)
    
test_backpack()

Contents: ['pencil', 'pen', 'paper', 'computer']


#### 
#### Problem 2

In [154]:
class Jetpack(Backpack):
    """A Jetpack object class. Inherits from the Backpack class. 
    A jetpack is similar to a backpack but stores less items because it can accept an amount
    of fuel that allows the person wearing it to fly.
    
    Attributes: 
        name (str): the name of the jetpack's owner.
        color (str): the color of the jetpack.
        max_size (int): maximum number of items in the jetpack. 
        contents (list): the contents of the jetpack.
        fuel (int): amount of fuel to be burned.
    """
    def __init__(self, name, color, max_size=2):
        """Set the name, color, max size, and initialize an empty list of contents.
        
        Parameters: 
            name (str): the name of the jetpack's owner.
            color (str): the color of the jetpack.
            max_size (int): maximum number of items in the jetpack. 
            fuel (int): amount of fuel to be burned.
        """
        Backpack.__init__(self, name, color, max_size)
        self.fuel = 10
        
    def fly(self, amount):
        """Accepts an amount of fuel to be burned and decrements the present fuel level by that amount."""
        if amount > self.fuel:
            print("Not enough fuel!")
        else: 
            new_fuel = self.fuel - amount
            self.fuel = new_fuel

    def dump(self):
        """Empties the jetpack contents list and fuel tank."""
        self.contents = []
        self.fuel = 0